version: "3"
services:

  npm:
    build: containers/npm
    ports:
      - 8888:8888
    volumes:
      - .:/var/app

  php_websocket:
    build: containers/php_websocket
    volumes:
      - .:/var/app


#  php_fpm:
#    build: containers/php_fpm
#    image: voting_php_fpm
#    environment:
#      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#      - COMPOSER_ALLOW_SUPERUSER=1
#    depends_on:
#      - db
#      - redis
#    networks:
#      default_network:
#    volumes:
#      - .:/var/app
#  php_fpm_debug:
#    build: containers/php_fpm_debug
#    environment:
#      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#      - COMPOSER_ALLOW_SUPERUSER=1
#    depends_on:
#      - redis
#      - php_fpm
#    networks:
#      default_network:
#    volumes:
#      - .:/var/app
#  redis:
#    image: redis:4.0.6
#    volumes:
#      - .:/var/app
#    command: ["redis-server", "/var/app/containers/redis/config/redis.conf"]
#    networks:
#      default_network:
#  nginx:
#    build: containers/nginx
#    depends_on:
#      - db
#      - redis
#      - php_fpm
#    volumes:
#      - .:/var/app
#    networks:
#      default_network:
#        aliases:
#          - internal.opensourcefees.com
networks:
  default_network:

