version: "3"
services:
  npm:
    build: containers/npm
    ports:
      - 8888:8888
    volumes:
      - .:/var/app:delegated
  php_websocket:
    build: containers/php_websocket
    volumes:
      - .:/var/app:delegated

networks:
  default_network:

